import { Roboto } from "next/font/google";
import "./globals.css";
import NavigationSidebar from "@/components/NavigationSidebar";
import { Providers } from "./providers";
import ScreenSizeGuard from "./ScreenSizeGuard";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const NAVIGATION_SIDEBAR_WIDTH = "150px";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} antialiased`}>
        <Providers>
          <ScreenSizeGuard>
            <NavigationSidebar width={NAVIGATION_SIDEBAR_WIDTH} />
            {children}
          </ScreenSizeGuard>
        </Providers>
      </body>
    </html>
  );
}
